cc_library(
    name = "day01",
    srcs = ["day01.cc"],
    hdrs = ["day01.h"],
    deps = [
        "@com_google_absl//absl/container:flat_hash_set",
        "@com_google_absl//absl/types:optional",
    ],
)

cc_test(
    name = "day01_test",
    srcs = ["day01_test.cc"],
    deps = [
        ":day01",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_binary(
    name = "day01_main",
    srcs = ["day01_main.cc"],
    deps = [
        ":day01",
    ],
)

cc_library(
    name = "day02",
    srcs = ["day02.cc"],
    hdrs = ["day02.h"],
    deps = [
        "@com_google_absl//absl/container:flat_hash_map",
        "@com_google_absl//absl/strings",
    ],
)

cc_test(
    name = "day02_test",
    srcs = ["day02_test.cc"],
    deps = [
        ":day02",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_binary(
    name = "day02_main",
    srcs = ["day02_main.cc"],
    deps = [
        ":day02",
    ],
)

cc_library(
    name = "day03",
    srcs = ["day03.cc"],
    hdrs = ["day03.h"],
    deps = [
        "@com_google_absl//absl/types:optional",
    ],
)

cc_test(
    name = "day03_test",
    srcs = ["day03_test.cc"],
    deps = [
        ":day03",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_binary(
    name = "day03_main",
    srcs = ["day03_main.cc"],
    deps = [
        ":day03",
    ],
)

cc_library(
    name = "day04",
    srcs = ["day04.cc"],
    hdrs = ["day04.h"],
    deps = [
    ],
)

cc_test(
    name = "day04_test",
    srcs = ["day04_test.cc"],
    deps = [
        ":day04",
        "@com_google_absl//absl/strings",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_binary(
    name = "day04_main",
    srcs = ["day04_main.cc"],
    deps = [
        ":day04",
    ],
)

cc_library(
    name = "day05",
    srcs = ["day05.cc"],
    hdrs = ["day05.h"],
    deps = [
    ],
)

cc_test(
    name = "day05_test",
    srcs = ["day05_test.cc"],
    deps = [
        ":day05",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_binary(
    name = "day05_main",
    srcs = ["day05_main.cc"],
    deps = [
        ":day05",
    ],
)

cc_library(
    name = "day07",
    srcs = ["day07.cc"],
    hdrs = ["day07.h"],
    deps = [
        "@com_google_absl//absl/strings",
    ],
)

cc_test(
    name = "day07_test",
    srcs = ["day07_test.cc"],
    deps = [
        ":day07",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_binary(
    name = "day07_main",
    srcs = ["day07_main.cc"],
    deps = [
        ":day07",
    ],
)

cc_library(
    name = "day08",
    srcs = ["day08.cc"],
    hdrs = ["day08.h"],
    deps = [
    ],
)

cc_test(
    name = "day08_test",
    srcs = ["day08_test.cc"],
    deps = [
        ":day08",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_binary(
    name = "day08_main",
    srcs = ["day08_main.cc"],
    deps = [
        ":day08",
    ],
)

cc_library(
    name = "day09",
    srcs = ["day09.cc"],
    hdrs = ["day09.h"],
    deps = [
    ],
)

cc_test(
    name = "day09_test",
    srcs = ["day09_test.cc"],
    deps = [
        ":day09",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_binary(
    name = "day09_main",
    srcs = ["day09_main.cc"],
    deps = [
        ":day09",
    ],
)

cc_library(
    name = "day10",
    srcs = ["day10.cc"],
    hdrs = ["day10.h"],
    deps = [
    ],
)

cc_test(
    name = "day10_test",
    srcs = ["day10_test.cc"],
    deps = [
        ":day10",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_binary(
    name = "day10_main",
    srcs = ["day10_main.cc"],
    deps = [
        ":day10",
    ],
)

cc_library(
    name = "day16",
    srcs = ["day16.cc"],
    hdrs = ["day16.h"],
    deps = [
        "@com_google_absl//absl/strings",
    ],
)

cc_test(
    name = "day16_test",
    srcs = ["day16_test.cc"],
    deps = [
        ":day16",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_binary(
    name = "day16_main",
    srcs = ["day16_main.cc"],
    deps = [
        ":day16",
    ],
)

cc_library(
    name = "day19",
    srcs = ["day19.cc"],
    hdrs = ["day19.h"],
    deps = [
        "@com_google_absl//absl/strings",
    ],
)

cc_test(
    name = "day19_test",
    srcs = ["day19_test.cc"],
    deps = [
        ":day19",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_binary(
    name = "day19_main",
    srcs = ["day19_main.cc"],
    deps = [
        ":day19",
    ],
)
