cc_library(
  name = "day1",
  hdrs = ["day1.h"],
  srcs = ["day1.cc"],
  deps = [
    "@com_google_absl//absl/container:flat_hash_set",
    "@com_google_absl//absl/types:optional",
  ],
)

cc_test(
  name = "day1_test",
  srcs = ["day1_test.cc"],
  deps = [
    ":day1",
    "@com_google_googletest//:gtest_main",
  ],
)

cc_binary(
  name = "day1_main",
  srcs = ["day1_main.cc"],
  deps = [
    ":day1",
  ],
)


cc_library(
  name = "day2",
  hdrs = ["day2.h"],
  srcs = ["day2.cc"],
  deps = [
    "@com_google_absl//absl/container:flat_hash_map",
    "@com_google_absl//absl/strings",
  ],
)

cc_test(
  name = "day2_test",
  srcs = ["day2_test.cc"],
  deps = [
    ":day2",
    "@com_google_googletest//:gtest_main",
  ],
)

cc_binary(
  name = "day2_main",
  srcs = ["day2_main.cc"],
  deps = [
    ":day2",
  ],
)


cc_library(
  name = "day3",
  hdrs = ["day3.h"],
  srcs = ["day3.cc"],
  deps = [
    "@com_google_absl//absl/types:optional",
  ],
)

cc_test(
  name = "day3_test",
  srcs = ["day3_test.cc"],
  deps = [
    ":day3",
    "@com_google_googletest//:gtest_main",
  ],
)

cc_binary(
  name = "day3_main",
  srcs = ["day3_main.cc"],
  deps = [
    ":day3",
  ],
)


cc_library(
  name = "day5",
  hdrs = ["day5.h"],
  srcs = ["day5.cc"],
  deps = [
  ],
)

cc_test(
  name = "day5_test",
  srcs = ["day5_test.cc"],
  deps = [
    ":day5",
    "@com_google_googletest//:gtest_main",
  ],
)

cc_binary(
  name = "day5_main",
  srcs = ["day5_main.cc"],
  deps = [
    ":day5",
  ],
)


cc_library(
  name = "day7",
  hdrs = ["day7.h"],
  srcs = ["day7.cc"],
  deps = [
      "@com_google_absl//absl/strings",
  ],
)

cc_test(
  name = "day7_test",
  srcs = ["day7_test.cc"],
  deps = [
    ":day7",
    "@com_google_googletest//:gtest_main",
  ],
)

cc_binary(
  name = "day7_main",
  srcs = ["day7_main.cc"],
  deps = [
    ":day7",
  ],
)


cc_library(
  name = "day8",
  hdrs = ["day8.h"],
  srcs = ["day8.cc"],
  deps = [
  ],
)

cc_test(
  name = "day8_test",
  srcs = ["day8_test.cc"],
  deps = [
    ":day8",
    "@com_google_googletest//:gtest_main",
  ],
)

cc_binary(
  name = "day8_main",
  srcs = ["day8_main.cc"],
  deps = [
    ":day8",
  ],
)
