cc_library(
  name = "day1",
  hdrs = ["day1.h"],
  srcs = ["day1.cc"],
  deps = [
    "@google_abseil//absl/container:flat_hash_set",
    "@google_abseil//absl/types:optional",
  ],
)

cc_test(
  name = "day1_test",
  srcs = ["day1_test.cc"],
  deps = [
    ":day1",
    "@google_test//:gtest_main",
  ],
)

cc_binary(
  name = "day1_main",
  srcs = ["day1_main.cc"],
  deps = [
    ":day1",
  ],
)


cc_library(
  name = "day2",
  hdrs = ["day2.h"],
  srcs = ["day2.cc"],
  deps = [
    "@google_abseil//absl/container:flat_hash_map",
    "@google_abseil//absl/strings",
  ],
)

cc_test(
  name = "day2_test",
  srcs = ["day2_test.cc"],
  deps = [
    ":day2",
    "@google_test//:gtest_main",
  ],
)

cc_binary(
  name = "day2_main",
  srcs = ["day2_main.cc"],
  deps = [
    ":day2",
  ],
)


cc_library(
  name = "day3",
  hdrs = ["day3.h"],
  srcs = ["day3.cc"],
  deps = [
    "@google_abseil//absl/types:optional",
  ],
)

cc_test(
  name = "day3_test",
  srcs = ["day3_test.cc"],
  deps = [
    ":day3",
    "@google_test//:gtest_main",
  ],
)

cc_binary(
  name = "day3_main",
  srcs = ["day3_main.cc"],
  deps = [
    ":day3",
  ],
)


cc_library(
  name = "day5",
  hdrs = ["day5.h"],
  srcs = ["day5.cc"],
  deps = [
  ],
)

cc_test(
  name = "day5_test",
  srcs = ["day5_test.cc"],
  deps = [
    ":day5",
    "@google_test//:gtest_main",
  ],
)

cc_binary(
  name = "day5_main",
  srcs = ["day5_main.cc"],
  deps = [
    ":day5",
  ],
)
