package(default_visibility = ["//visibility:public"])

cc_library(
    name = "bitset",
    srcs = [],
    hdrs = ["bitset.h"],
    deps = [],
)

cc_test(
    name = "bitset_test",
    srcs = ["bitset_test.cc"],
    deps = [
        ":bitset",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_library(
    name = "point",
    srcs = [],
    hdrs = ["point.h"],
    deps = [],
)

cc_test(
    name = "point_test",
    srcs = ["point_test.cc"],
    deps = [
        ":point",
        "@com_google_googletest//:gtest_main",
    ],
)
