cc_library(
    name = "day01",
    srcs = ["day01.cc"],
    hdrs = ["day01.h"],
    deps = [],
)

cc_test(
    name = "day01_test",
    srcs = ["day01_test.cc"],
    deps = [
        ":day01",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_binary(
    name = "day01_main",
    srcs = ["day01_main.cc"],
    deps = [
        ":day01",
    ],
)

cc_library(
    name = "day02",
    srcs = ["day02.cc"],
    hdrs = ["day02.h"],
    deps = [],
)

cc_test(
    name = "day02_test",
    srcs = ["day02_test.cc"],
    deps = [
        ":day02",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_binary(
    name = "day02_main",
    srcs = ["day02_main.cc"],
    deps = [
        ":day02",
    ],
)

cc_library(
    name = "day03",
    srcs = ["day03.cc"],
    hdrs = ["day03.h"],
    deps = [],
)

cc_test(
    name = "day03_test",
    srcs = ["day03_test.cc"],
    deps = [
        ":day03",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_binary(
    name = "day03_main",
    srcs = ["day03_main.cc"],
    deps = [
        ":day03",
    ],
)

cc_library(
    name = "day04",
    srcs = ["day04.cc"],
    hdrs = ["day04.h"],
    deps = [
        "@com_google_absl//absl/strings",
    ],
)

cc_test(
    name = "day04_test",
    srcs = ["day04_test.cc"],
    deps = [
        ":day04",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_binary(
    name = "day04_main",
    srcs = ["day04_main.cc"],
    deps = [
        ":day04",
    ],
)

cc_library(
    name = "day05",
    srcs = ["day05.cc"],
    hdrs = ["day05.h"],
    deps = [],
)

cc_test(
    name = "day05_test",
    srcs = ["day05_test.cc"],
    deps = [
        ":day05",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_binary(
    name = "day05_main",
    srcs = ["day05_main.cc"],
    deps = [
        ":day05",
    ],
)

cc_binary(
    name = "day05_bench",
    srcs = ["day05_bench.cc"],
    deps = [
        ":day05",
        "@com_google_benchmark//:benchmark_main",
    ],
)

cc_library(
    name = "day06",
    srcs = ["day06.cc"],
    hdrs = ["day06.h"],
    deps = [],
)

cc_test(
    name = "day06_test",
    srcs = ["day06_test.cc"],
    deps = [
        ":day06",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_binary(
    name = "day06_main",
    srcs = ["day06_main.cc"],
    deps = [
        ":day06",
    ],
)
