cc_library(
    name = "day01",
    srcs = ["day01.cc"],
    hdrs = ["day01.h"],
    deps = [],
)

cc_test(
    name = "day01_test",
    srcs = ["day01_test.cc"],
    deps = [
        ":day01",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_binary(
    name = "day01_main",
    srcs = ["day01_main.cc"],
    deps = [
        ":day01",
    ],
)

cc_library(
    name = "day02",
    srcs = ["day02.cc"],
    hdrs = ["day02.h"],
    deps = [],
)

cc_test(
    name = "day02_test",
    srcs = ["day02_test.cc"],
    deps = [
        ":day02",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_binary(
    name = "day02_main",
    srcs = ["day02_main.cc"],
    deps = [
        ":day02",
    ],
)


cc_library(
    name = "day03",
    srcs = ["day03.cc"],
    hdrs = ["day03.h"],
    deps = [],
)

cc_test(
    name = "day03_test",
    srcs = ["day03_test.cc"],
    deps = [
        ":day03",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_binary(
    name = "day03_main",
    srcs = ["day03_main.cc"],
    deps = [
        ":day03",
    ],
)
